server:
  port: 9083
dubbo:
  application:
    name: sso-consumer
  registry:
    address: zookeeper://47.105.157.189:2181
spring:
  redis:
    host: 47.105.157.189
    port: 6379
    password: java1906
    jedis:
      pool:
        max-active: 10
  rabbitmq:
    host: 47.105.157.189
    port: 5672
    username: java1906
    password: 123456
    virtual-host: j1906