spring:
  rabbitmq:
    host: 47.105.157.189
    port: 5672
    username: java1906
    password: 123456
    virtual-host: j1906
  redis:
    host: 47.105.157.189
    port: 6379
    password: java1906
    jedis:
      pool:
        max-active: 20
server:
  port: 8085
sms:
  account: JSM42639
  password: l43d7myq
  veryCode: irnsloy2kjhd
  http_url: http://112.74.76.186:8030
  tplId: JSM42639-0001